### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ghost** [DaddyImPregnant/Atlantic#2]
**Describe the bug**
When a player throws an enderpearl and on cooldown, it doesn't it give the enderpearl back
**To Reproduce**
1. Throw enderpearl and get on cooldown

**Expected behavior**
Cancel enderpearl event.

**Screenshots**
No Screenshots needed
**Server info (please complete the following information):**
 - Server version: 1.7.10
 - Jar type Exospigot
 - Atlantic version 1.0.4

**Additional context**
No further information

**Comment by Scifi9902** [comment]
Not a bug, theirs an option in the config to enable or disable modified launch event, set it to false to fix it. the feature is there for spigots such as mSpigot which automatically refund the item upon cancellation of the event.
