### ISSUE TITLE
getPlayerPacket in 1.16

### ISSUE THREAD

**Issue by xCodiq** [DaddyImPregnant/Atlantic#3]
private static Packet getPlayerPacket(String name) {
		//TODO THIS DOESN'T WORK YET LMAOOO
		PacketPlayOutPlayerInfo packet = new PacketPlayOutPlayerInfo();

		Field action;
		Field username;
		Field player;
		try {
			action = PacketPlayOutPlayerInfo.class.getDeclaredField("action");
			username = PacketPlayOutPlayerInfo.class.getDeclaredField("username");
			player = PacketPlayOutPlayerInfo.class.getDeclaredField("player");

			action.setAccessible(true);
			username.setAccessible(true);
			player.setAccessible(true);

			action.set(packet, 0);
			username.set(packet, name);
			player.set(packet, new GameProfile(UUID.randomUUID(), name));
		} catch (NoSuchFieldException e) {
			e.printStackTrace();
			return null;
		} catch (IllegalAccessException e) {
			e.printStackTrace();
		}

		return packet;
	}

Do you know how to do this in 1.16?

**Comment by InvisRaidinq** [comment]
Why exactly are you trying to run a HCF core on 1.16 in the first place?

**Comment by xCodiq** [comment]
Its just the tablist part I need

**Comment by Scifi9902** [comment]
The tablist is open-sourced and owned by a person called BizarreAlex, you will have to contact them as it is not our code.
