### ISSUE TITLE
[Bug] Could you help me fix the pom, new to maven and i dont really understand :) thanks

### ISSUE THREAD

**Issue by nmateo** [DaddyImPregnant/Atlantic#4]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server info (please complete the following information):**
 - Server version: [e.g. 1.7.10-SNAPSHOT]
 - Jar type [e.g. Exospigot]
 - Atlantic version [e.g. 1.0.3-SNAPSHOT]

**Additional context**

**Comment by InvisRaidinq** [comment]
Just saying you're supposed to fill in the issues under the headings, not just copy and paste it and put it in the title. What exactly is wrong with the POM?

A word of advice, if you don't know how to use maven then just use the pre-compiled JAR, all messages are configurable.

**Comment by nmateo** [comment]
i found out myself :)
